# Generated by Django 4.1.5 on 2023-01-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDD_DJANGO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
