# Generated by Django 4.1.5 on 2023-01-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDD_DJANGO', '0003_user_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
